#!/bin/sh

#python compare_T2tt_limits.py --outfile=etc/tmp.pdf --files="multiIsoVL:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/multiIsoL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIsoM:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/multiIsoM_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIsoT:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/multiIsoT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIsoVL:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/multiIsoVL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIsoVT:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/multiIsoVT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root"
#python compare_T2tt_limits.py --outfile=etc/tmp.png --files="multiIsoVL:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/multiIsoL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIsoM:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/multiIsoM_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIsoT:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/multiIsoT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIsoVL:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/multiIsoVL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIsoVT:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/multiIsoVT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root"

#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met100-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met100-metSig4-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met100-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met100-metSig6-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met120-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met120-metSig4-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met120-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met140-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met60-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met60-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met60-metSig6-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met60-metSig7-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met60-metSig8-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met80-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met80-metSig4-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met80-metSig6-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met80-metSig8-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root

#,MET>100,MetSig>5:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met100-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#,MET>60,MetSig>5:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met60-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root

#python compare_T2tt_limits.py --outfile=etc/MetMetSig.png --files="MET>100 & MetSig>3:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met100-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>100 & MetSig>6:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met100-metSig6-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>120 & MetSig>3:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met120-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>120 & MetSig>5:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met120-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>140 & MetSig>3:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met140-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>60 & MetSig>3:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met60-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>60 & MetSig>8:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met60-metSig8-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>80 & MetSig>3:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met80-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>80 & MetSig>5:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>80 & MetSig>8:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met80-metSig8-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root"
python compare_T2tt_limits.py --outfile=etc/multiIso.png --files="nominal:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso VL:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoVL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso L:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso M:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoM_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso T:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso VT:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoVT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root"
python compare_T2tt_limits.py --outfile=etc/multiIso.pdf --files="nominal:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso VL:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoVL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso L:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso M:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoM_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso T:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso VT:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoVT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root"
