#!/bin/sh



#,MET>100,MetSig>5:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met100-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root
#,MET>60,MetSig>5:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met60-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root

#python compare_T2tt_limits.py --outfile=etc/MetMetSig.png --files="MET>100 & MetSig>3:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met100-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>100 & MetSig>6:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met100-metSig6-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>120 & MetSig>3:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met120-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>120 & MetSig>5:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met120-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>140 & MetSig>3:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met140-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>60 & MetSig>3:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met60-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>60 & MetSig>8:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met60-metSig8-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>80 & MetSig>3:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met80-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>80 & MetSig>5:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,MET>80 & MetSig>8:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test3/isOS-nJets2p-nbtag1p-met80-metSig8-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root"

#python compare_T2tt_limits.py --outfile=etc/multiIso.png --files="nominal:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso VL:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoVL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso L:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso M:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoM_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso T:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso VT:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoVT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root"
#python compare_T2tt_limits.py --outfile=etc/multiIso.pdf --files="nominal:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso VL:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoVL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso L:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoL_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso M:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoM_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso T:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,multiIso VT:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/multiIsoVT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root"

#python compare_T2tt_limits.py --outfile=etc/multiIso_2.pdf,etc/multiIso_2.png,etc/multiIso_2.root --files="nominal:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test5/isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,Mu(M)/Ele(M):/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test6/multiIsoMM_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,Mu(M)/Ele(T):/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test6/multiIsoMT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,Mu(T)/Ele(M):/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test6/multiIsoTM_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,Mu(T)/Ele(VT):/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test6/multiIsoTVT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,Mu(VT)/Ele(T):/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test6/multiIsoVTT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,Mu(VT)/Ele(VT):/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test6/multiIsoVTVT_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,relIso04sm12:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test6/relIso04sm12_isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root"
python compare_T2tt_limits.py --outfile=etc/metsig.pdf,etc/metSig.png,etc/metSig.root --files="metSig>3:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test6/isOS-nJets2p-nbtag1p-met80-metSig3-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,metsig>5:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test6/isOS-nJets2p-nbtag1p-met80-metSig5-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root,metSig>8:/afs/hephy.at/data/rschoefbeck01/StopsDilepton/results/test6/isOS-nJets2p-nbtag1p-met80-metSig8-dPhiJet0-dPhiJet-mll20/limits/flavSplit_almostAllReg/T2tt_limitResults.root"
