python METsig_study_estimates.py --selectEstimator TTJets       --MET 80 --METsig 0
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 0
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 5
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 7
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 8
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 9
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 10
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 11
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 12
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 15
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 18
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 21
python METsig_study_estimates.py --selectEstimator TTJets       --MET 0 --METsig 25

python METsig_study_estimates.py --selectEstimator DY       --MET 0 --METsig 5
python METsig_study_estimates.py --selectEstimator DY       --MET 0 --METsig 12
python METsig_study_estimates.py --selectEstimator DY       --MET 0 --METsig 15
python METsig_study_estimates.py --selectEstimator DY       --MET 0 --METsig 18
python METsig_study_estimates.py --selectEstimator DY       --MET 0 --METsig 21
python METsig_study_estimates.py --selectEstimator DY       --MET 0 --METsig 25
