./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=allZ --mode=doubleMu"
./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=allZ --mode=doubleEle"
./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=onZ --mode=doubleMu"
./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=onZ --mode=doubleEle"
./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=offZ --mode=doubleEle"
./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=offZ --mode=doubleMu"
./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=allZ --mode=muEle"
./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=onZ --mode=muEle"
./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=offZ --mode=muEle"
./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=allZ --mode=sameFlavour"
./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=onZ --mode=sameFlavour"
./submit.sh "python simple1DPlots.py $1 $2 $3 --zMode=offZ --mode=sameFlavour"
./submit.sh "python simple1DPlots.py $1 $2 $3 --mode=dilepton"
