#!/bin/sh
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 01 --nbtag 0"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 01 --nbtag 0"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 2p --nbtag 0"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=muEle --zMode=allZ --njet 01 --nbtag 0"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=muEle --zMode=allZ --njet 2p --nbtag 0"
#
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=muEle --zMode=allZ --njet 01 --nbtag 1p"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=dilepton --njet 01 --nbtag 1p"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 01 --nbtag 1p"
#
#./submit.sh "python simple1DPlots.py $1 --mode=dilepton --njet 2p --nbtag 1p"
#./submit.sh "python simple1DPlots.py $1 --mode=dilepton --njet 2p --nbtag 0"
#./submit.sh "python simple1DPlots.py $1 --mode=dilepton --njet 1p --nbtag 0"
#./submit.sh "python simple1DPlots.py $1 --mode=dilepton --njet 0p --nbtag 0"
#./submit.sh "python simple1DPlots.py $1 --mode=dilepton --njet 0 --nbtag 0"
#./submit.sh "python simple1DPlots.py $1 --mode=dilepton --njet 1 --nbtag 0"

#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 01 --nbtag 0 --highMT2ll"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 01 --nbtag 0 --highMT2ll"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 2p --nbtag 0 --highMT2ll"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0 --highMT2ll"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=muEle --zMode=allZ --njet 01 --nbtag 1p --highMT2ll"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=dilepton --njet 01 --nbtag 1p --highMT2ll"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 01 --nbtag 1p --highMT2ll"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=muEle --zMode=allZ --njet 01 --nbtag 0 --highMT2ll"
#./submit.sh "python simple1DPlots.py $1 --splitDiBoson --mode=muEle --zMode=allZ --njet 2p --nbtag 0 --highMT2ll"

./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=offZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=offZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=offZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=offZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=offZ --njet 1 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=onZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=onZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=onZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=onZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=onZ --njet 1 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=allZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=allZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=allZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=allZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=allZ --njet 1 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=offZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=offZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=offZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=offZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=offZ --njet 1 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=onZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=onZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=onZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=onZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=onZ --njet 1 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=allZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=allZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=allZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=allZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=allZ --njet 1 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 1 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 1 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 1 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=offZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=offZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=offZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=offZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=offZ --njet 1 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=onZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=onZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=onZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=onZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=onZ --njet 1 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 2p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 1p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 0p --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 0 --nbtag 0"
./submit.sh "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet  --nbtag 0"
