#!/bin/sh

# low njet, btag 0
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 01 --nbtag 0"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 01 --nbtag 0"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 01 --nbtag 0"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=muEle --zMode=allZ --njet 01 --nbtag 0"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode-dilepton --njet 01 --nbtag 0"

# high njet, btag 0
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 2p --nbtag 0"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 2p --nbtag 0"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=muEle --zMode=allZ --njet 2p --nbtag 0"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode-dilepton --njet 2p --nbtag 0"

# low njet, btag 1p
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 01 --nbtag 1p"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 01 --nbtag 1p"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 01 --nbtag 1p"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=muEle --zMode=allZ --njet 01 --nbtag 1p"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode-dilepton --njet 01 --nbtag 1p"

# high njet, btag 1p
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 2p --nbtag 1p"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 1p"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 2p --nbtag 1p"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode=muEle --zMode=allZ --njet 2p --nbtag 1p"
./submit.sh "python systematic1DPlots.py $1 --sysScaling --splitDiBoson --mode-dilepton --njet 2p --nbtag 1p"


#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 1 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 1 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=offZ --njet 1 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 1 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 1 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=onZ --njet 1 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 1 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 1 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleMu --zMode=allZ --njet 1 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 1 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 1 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=offZ --njet 1 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 1 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 1 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=onZ --njet 1 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 1 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 1 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=doubleEle --zMode=allZ --njet 1 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 1 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 1 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=offZ --njet 1 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 1 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 1 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=onZ --njet 1 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 1 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 1 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=sameFlavour --zMode=allZ --njet 1 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 1 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 1 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=offZ --njet 1 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 1 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 1 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=onZ --njet 1 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 2p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 2p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 2p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 1p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 1p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 1p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 0p --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 0p --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 0p --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 0 --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 0 --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet 0 --nbtag 0 --noScaling --highMT2ll"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet  --nbtag 0"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet  --nbtag 0 --noScaling"
#./submit.sh "python systematic1DPlots.py $1 --mode=muEle --zMode=allZ --njet  --nbtag 0 --noScaling --highMT2ll"
