#!/bin/sh
submitBatch.py "python simple1DPlots.py --overwrite $1 $2 --mode=doubleMu --zMode=offZ"
submitBatch.py "python simple1DPlots.py --overwrite $1 $2 --mode=doubleMu --zMode=onZ"
submitBatch.py "python simple1DPlots.py --overwrite $1 $2 --mode=doubleMu --zMode=allZ"
submitBatch.py "python simple1DPlots.py --overwrite $1 $2 --mode=doubleEle --zMode=offZ"
submitBatch.py "python simple1DPlots.py --overwrite $1 $2 --mode=doubleEle --zMode=onZ"
submitBatch.py "python simple1DPlots.py --overwrite $1 $2 --mode=doubleEle --zMode=allZ"
submitBatch.py "python simple1DPlots.py --overwrite $1 $2 --mode=muEle --zMode=allZ"
submitBatch.py "python simple1DPlots.py --overwrite $1 $2 --mode=sameFlavour --zMode=offZ"
submitBatch.py "python simple1DPlots.py --overwrite $1 $2 --mode=sameFlavour --zMode=onZ"
submitBatch.py "python simple1DPlots.py --overwrite $1 $2 --mode=sameFlavour --zMode=allZ"
submitBatch.py "python simple1DPlots.py --overwrite $1 $2 --mode=dilepton"

## TTbarDM
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_10 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_10 --overwrite $1 $2 --mode=doubleMu --zMode=offZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_10"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_20 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_20 --overwrite $1 $2 --mode=doubleMu --zMode=offZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_20"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_50 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_50 --overwrite $1 $2 --mode=doubleMu --zMode=offZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_50"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_10 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_10 --overwrite $1 $2 --mode=doubleEle --zMode=offZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_10"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_20 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_20 --overwrite $1 $2 --mode=doubleEle --zMode=offZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_20"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_50 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_50 --overwrite $1 $2 --mode=doubleEle --zMode=offZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_50"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_10 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_10 --overwrite $1 $2 --mode=muEle --zMode=allZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_10"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_20 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_20 --overwrite $1 $2 --mode=muEle --zMode=allZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_20"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_50 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_50 --overwrite $1 $2 --mode=muEle --zMode=allZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_50"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_10 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_10 --overwrite $1 $2 --mode=sameFlavour --zMode=offZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_10"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_20 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_20 --overwrite $1 $2 --mode=sameFlavour --zMode=offZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_20"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_50 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_50 --overwrite $1 $2 --mode=sameFlavour --zMode=offZ  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_50"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_10 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_10 --overwrite $1 $2 --mode=dilepton  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_10"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_20 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_20 --overwrite $1 $2 --mode=dilepton  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_20"
#submitBatch.py "python simple1DPlots.py --signals TTbarDMJets_scalar_Mchi_1_Mphi_50 TTbarDMJets_pseudoscalar_Mchi_1_Mphi_50 --overwrite $1 $2 --mode=dilepton  --plot_directory=80X_v12_TTDM/Mchi_1_Mphi_50"

##mIsoWP
#python simple1DPlots.py  --noLoop --overwrite --mIsoWP 0 &
#python simple1DPlots.py  --noLoop --overwrite --mIsoWP 1 &
#python simple1DPlots.py  --noLoop --overwrite --mIsoWP 2 &
#python simple1DPlots.py  --noLoop --overwrite --mIsoWP 3 &
#python simple1DPlots.py  --noLoop --overwrite --mIsoWP 4 &
#python simple1DPlots.py  --noLoop --overwrite --mIsoWP 5 &
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --mIsoWP 0"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --mIsoWP 1"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --mIsoWP 2"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --mIsoWP 3"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --mIsoWP 4"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --mIsoWP 5"

#Isabell
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=def --mode=doubleMu --zMode=onZ"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=none --mode=doubleMu --zMode=onZ"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=lead --mode=doubleMu --zMode=onZ"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=inv --mode=doubleMu --zMode=onZ"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=def --mode=doubleEle --zMode=onZ"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=none --mode=doubleEle --zMode=onZ"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=lead --mode=doubleEle --zMode=onZ"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=inv --mode=doubleEle --zMode=onZ"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=def --mode=muEle --zMode=onZ"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=none --mode=muEle --zMode=onZ"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=lead --mode=muEle --zMode=onZ"
#submitBatch.py "python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=inv --mode=muEle --zMode=onZ"

#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=def --mode=doubleMu --zMode=onZ &
#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=none --mode=doubleMu --zMode=onZ &
#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=lead --mode=doubleMu --zMode=onZ &
#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=inv --mode=doubleMu --zMode=onZ &
#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=def --mode=doubleEle --zMode=onZ &
#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=none --mode=doubleEle --zMode=onZ &
#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=lead --mode=doubleEle --zMode=onZ &
#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=inv --mode=doubleEle --zMode=onZ &
#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=def --mode=muEle --zMode=onZ &
#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=none --mode=muEle --zMode=onZ &
#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=lead --mode=muEle --zMode=onZ &
#python simple1DPlots.py  --noLoop --overwrite --nbtag=0 --dPhi=inv --mode=muEle --zMode=onZ &

#diboson CR
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ  --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0 --dPhi=none"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ  --njet 2p --nbtag 0 --dPhi=none"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 2p --nbtag 0 --dPhi=none"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0 --dPhi=inv"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ  --njet 2p --nbtag 0 --dPhi=inv"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 2p --nbtag 0 --dPhi=inv"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ  --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 1p --nbtag 0 --dPhi=none"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ  --njet 1p --nbtag 0 --dPhi=none"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 1p --nbtag 0 --dPhi=none"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 1p --nbtag 0 --dPhi=inv"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ  --njet 1p --nbtag 0 --dPhi=inv"
#submitBatch.py "python simple1DPlots.py  --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 1p --nbtag 0 --dPhi=inv"

#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 01 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 01 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 01 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 2p --nbtag 0"
#
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 01 --nbtag 1p"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=dilepton --njet 01 --nbtag 1p"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 01 --nbtag 1p"
#
#submitBatch.py "python simple1DPlots.py $1 --noLoop --mode=dilepton --njet 2p --nbtag 1p"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --mode=dilepton --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --mode=dilepton --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --mode=dilepton --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --mode=dilepton --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --mode=dilepton --njet 1 --nbtag 0"
#
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 01 --nbtag 0 --highMT2ll"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 01 --nbtag 0 --highMT2ll"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 2p --nbtag 0 --highMT2ll"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0 --highMT2ll"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 01 --nbtag 1p --highMT2ll"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=dilepton --njet 01 --nbtag 1p --highMT2ll"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 01 --nbtag 1p --highMT2ll"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 01 --nbtag 0 --highMT2ll"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 2p --nbtag 0 --highMT2ll"
#
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=offZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=offZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=offZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=offZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=offZ --njet 1 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=onZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=onZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=onZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=onZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=onZ --njet 1 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=allZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=allZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=allZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=allZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleMu --zMode=allZ --njet 1 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=offZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=offZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=offZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=offZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=offZ --njet 1 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=onZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=onZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=onZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=onZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=onZ --njet 1 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=allZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=allZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=allZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=allZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=doubleEle --zMode=allZ --njet 1 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=offZ --njet 1 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=onZ --njet 1 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=sameFlavour --zMode=allZ --njet 1 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=offZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=offZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=offZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=offZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=offZ --njet 1 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=onZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=onZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=onZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=onZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=onZ --njet 1 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 2p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 1p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 0p --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet 0 --nbtag 0"
#submitBatch.py "python simple1DPlots.py $1 --noLoop --splitDiBoson --mode=muEle --zMode=allZ --njet  --nbtag 0"
