#python nanoSignalSplitting.py --year 2016 --fastSim --T2tt         --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2016_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_150to250 # SPLIT2
#python nanoSignalSplitting.py --year 2016 --fastSim --T2tt         --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2016_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_250to350 # SPLIT2
#python nanoSignalSplitting.py --year 2016 --fastSim --T2tt         --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2016_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_350to400
#python nanoSignalSplitting.py --year 2016 --fastSim --T2tt         --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2016_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_400to1200 # SPLIT12
#python nanoSignalSplitting.py --year 2016 --fastSim --T2bW         --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2016_nano_v0p23 --skim dilep --samples SMS_T2bW #SPLIT8
#python nanoSignalSplitting.py --year 2016 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2016_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p05 #SPLIT10
#python nanoSignalSplitting.py --year 2016 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2016_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p05_mN1_700_1000 #SPLIT10
#python nanoSignalSplitting.py --year 2016 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2016_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p5 #SPLIT10
#python nanoSignalSplitting.py --year 2016 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2016_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p5_mN1_700_1300 #SPLIT10
#python nanoSignalSplitting.py --year 2016 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2016_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p95 #SPLIT10
#python nanoSignalSplitting.py --year 2016 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2016_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p95_mN1_700_1600 #SPLIT10

#python nanoSignalSplitting.py --year 2017 --fastSim --T2tt   --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2017_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_150to250 # SPLIT2
#python nanoSignalSplitting.py --year 2017 --fastSim --T2tt   --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2017_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_250to350 # SPLIT2
#python nanoSignalSplitting.py --year 2017 --fastSim --T2tt   --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2017_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_350to400 # SPLIT2
#python nanoSignalSplitting.py --year 2017 --fastSim --T2tt   --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2017_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_400to1200 # SPLIT8
#python nanoSignalSplitting.py --year 2017 --fastSim --T2bW   --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2017_nano_v0p23 --skim dilep --samples SMS_T2bW #SPLIT8
#python nanoSignalSplitting.py --year 2017 --fastSim --T8bbllnunu --inputDir /afs/hephy.at/data/cms04/nanoTuples/  --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2017_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p05 #SPLIT4
#python nanoSignalSplitting.py --year 2017 --fastSim --T8bbllnunu --inputDir /afs/hephy.at/data/cms04/nanoTuples/  --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2017_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p05_mN1_700_1000
python nanoSignalSplitting.py --year 2017 --fastSim --T8bbllnunu --inputDir /afs/hephy.at/data/cms04/nanoTuples/  --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2017_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p5 #SPLIT14
python nanoSignalSplitting.py --year 2017 --fastSim --T8bbllnunu --inputDir /afs/hephy.at/data/cms04/nanoTuples/  --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2017_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p5_mN1_700_1300
#python nanoSignalSplitting.py --year 2017 --fastSim --T8bbllnunu --inputDir /afs/hephy.at/data/cms04/nanoTuples/  --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2017_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p95 #SPLIT4
#python nanoSignalSplitting.py --year 2017 --fastSim --T8bbllnunu --inputDir /afs/hephy.at/data/cms04/nanoTuples/  --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2017_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p95_mN1_700_1600
#
#python nanoSignalSplitting.py --year 2018 --fastSim --T2tt         --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2018_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_150to250 # SPLIT10
#python nanoSignalSplitting.py --year 2018 --fastSim --T2tt         --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2018_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_250to350 # SPLIT2
#python nanoSignalSplitting.py --year 2018 --fastSim --T2tt         --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2018_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_350to400 # SPLIT2
#python nanoSignalSplitting.py --year 2018 --fastSim --T2tt         --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2018_nano_v0p23 --skim dilep --samples SMS_T2tt_mStop_400to1200 # SPLIT12
#python nanoSignalSplitting.py --year 2018 --fastSim --T2bW         --inputDir  /afs/hephy.at/data/cms06/nanoTuples/ --targetDir /afs/hephy.at/data/cms06/nanoTuples/ --processingEra stops_2018_nano_v0p23 --skim dilep --samples SMS_T2bW #SPLIT8
#python nanoSignalSplitting.py --year 2018 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2018_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p05 #SPLIT4
#python nanoSignalSplitting.py --year 2018 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2018_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p05_mN1_700_1000 #SPLIT4
#python nanoSignalSplitting.py --year 2018 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2018_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p5 #SPLIT4
#python nanoSignalSplitting.py --year 2018 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2018_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p5_mN1_700_1300 #SPLIT4
#python nanoSignalSplitting.py --year 2018 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2018_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p95_mN1_0_650 #SPLIT4
#python nanoSignalSplitting.py --year 2018 --fastSim --T8bbllnunu   --inputDir  /afs/hephy.at/data/cms04/nanoTuples/ --targetDir /afs/hephy.at/data/cms04/nanoTuples/ --processingEra stops_2018_nano_v0p23 --skim dilep --samples SMS_T8bbllnunu_XCha0p5_XSlep0p95_mN1_700_1600 #SPLIT4
