##############################################
# Plots in SUS-19-011 (with post fit scaling)
##############################################

# Using caches which can be found here: /afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/

python systematicVariation_summed.py --plot_directory v0p22 --signal T2tt --SFUnc SF.pkl --beta postFit --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p22_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p22_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p22_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
python systematicVariation_summed.py --plot_directory v0p19 --SFUnc SF.pkl --beta postFit --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
python systematicVariation_summed.py --plot_directory v0p23 --SFUnc SF.pkl --beta postFit --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p23_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p23_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p23_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"
python systematicVariation_summed.py --plot_directory v0p19 --SFUnc SF.pkl --beta postFit --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"
python systematicVariation_summed.py --plot_directory v0p22 --SFUnc SF.pkl --beta postFit --fitChi2 --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p22_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p22_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p22_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ"







################################################
#             AN (and miscellaneous)
################################################

# using post fit scaling
python systematicVariation_summed.py --plot_directory v0p22 --signal T2tt --SFUnc SF.pkl --beta postFit --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/CR_v0p22/2016/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/CR_v0p22/2017/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/CR_v0p22/2018/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"

# DY CR
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
python systematicVariation_summed.py --plot_directory v0p19 --normalize --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
python systematicVariation_summed.py --plot_directory v0p19 --normalize --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
# MetSig plots
python systematicVariation_summed.py --plot_directory v0p22 --scaling mc --variation_scaling --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p22_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p22_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p22_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
# mt2ll100
python systematicVariation_summed.py --plot_directory v0p23 --normalize --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p23_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p23_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p23_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"
python systematicVariation_summed.py --plot_directory v0p22 --normalize --fitChi2 --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p22_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p22_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p22_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ"
# sideband
python systematicVariation_summed.py --plot_directory v0p22 --normalize --selection lepSel-POGMetSig12-njet01-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-allZ --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p22_reweightPUCentral/lepSel-POGMetSig12-njet01-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-allZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p22_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet01-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-allZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p22_reweightPUVUp/lepSel-POGMetSig12-njet01-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-allZ/"
# DY btag multiplicity
python systematicVariation_summed.py --plot_directory v0p22 --normalize --selection lepSel-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p22_reweightPUCentral/lepSel-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p22_reweightPUCentral/lepSel-badEEJetVeto-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p22_reweightPUVUp/lepSel-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ"
python systematicVariation_summed.py --plot_directory v0p22 --normalize --selection lepSel-POGMetSigTo12-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p22_reweightPUCentral/lepSel-POGMetSigTo12-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p22_reweightPUCentral/lepSel-POGMetSigTo12-badEEJetVeto-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p22_reweightPUVUp/lepSel-POGMetSigTo12-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ"
# CR
python systematicVariation_summed.py --plot_directory v0p22 --signal T2tt --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --beta noScaling --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p22_T2tt_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p22_T2tt_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p22_T2tt_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" --beta noScaling
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
# low S
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
# mt2ll100
python systematicVariation_summed.py --plot_directory v0p19 --normalize --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100"
python systematicVariation_summed.py --plot_directory v0p19 --normalize --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"
# SR
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
# SR mt2ll100
python systematicVariation_summed.py --plot_directory v0p19 --normalize --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2016/v0p19_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2017/v0p19_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/systematicPlots/Run2018/v0p19_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"























########################################################################################
# Using Private Caches
########################################################################################

# PAPER
# ================

python systematicVariation_summed.py --plot_directory v0p22 --signal T2tt --SFUnc "/afs/hephy.at/data/cms05/StopsDileptonLegacy/results/v8/SF.pkl" --beta postFit --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p22_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p22_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p22_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
python systematicVariation_summed.py --plot_directory v0p19 --SFUnc "/afs/hephy.at/data/cms05/StopsDileptonLegacy/results/v8/SF.pkl" --beta postFit --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
python systematicVariation_summed.py --plot_directory v0p23 --SFUnc "/afs/hephy.at/data/cms05/StopsDileptonLegacy/results/v8/SF.pkl" --beta postFit --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p23_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p23_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p23_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"
python systematicVariation_summed.py --plot_directory v0p19 --SFUnc "/afs/hephy.at/data/cms05/StopsDileptonLegacy/results/v8/SF.pkl" --beta postFit --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"
python systematicVariation_summed.py --plot_directory v0p22 --SFUnc "/afs/hephy.at/data/cms05/StopsDileptonLegacy/results/v8/SF.pkl" --beta postFit --fitChi2 --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p22_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p22_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p22_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ"
















# AN
# ========================


# DY CR
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
python systematicVariation_summed.py --plot_directory v0p19 --normalize --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
python systematicVariation_summed.py --plot_directory v0p19 --normalize --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"



# MetSig plots
python systematicVariation_summed.py --plot_directory v0p22 --scaling mc --variation_scaling --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p22_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p22_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p22_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
python systematicVariation_summed.py --plot_directory v0p22 --signal T2tt --SFUnc "/afs/hephy.at/data/cms05/StopsDileptonLegacy/results/v8/SF.pkl" --beta postFit --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/data/cms05/StopsDileptonLegacy/CR_v0p22/2016/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/CR_v0p22/2017/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/data/cms05/StopsDileptonLegacy/CR_v0p22/2018/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
# mt2ll100
python systematicVariation_summed.py --plot_directory v0p23 --normalize --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p23_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p23_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p23_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"
python systematicVariation_summed.py --plot_directory v0p22 --normalize --fitChi2 --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p22_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p22_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p22_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ"

# 28.2.2020 sideband
python systematicVariation_summed.py --plot_directory v0p22 --normalize --selection lepSel-POGMetSig12-njet01-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-allZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p22_reweightPUCentral/lepSel-POGMetSig12-njet01-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-allZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p22_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet01-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-allZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p22_reweightPUVUp/lepSel-POGMetSig12-njet01-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-allZ/"

# 02.24.2020 DY btag multiplicity
python systematicVariation_summed.py --plot_directory v0p22 --normalize --selection lepSel-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p22_reweightPUCentral/lepSel-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p22_reweightPUCentral/lepSel-badEEJetVeto-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p22_reweightPUVUp/lepSel-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ"

python systematicVariation_summed.py --plot_directory v0p22 --normalize --selection lepSel-POGMetSigTo12-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p22_reweightPUCentral/lepSel-POGMetSigTo12-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p22_reweightPUCentral/lepSel-POGMetSigTo12-badEEJetVeto-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p22_reweightPUVUp/lepSel-POGMetSigTo12-njet2p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-onZ"

# CR
python systematicVariation_summed.py --plot_directory v0p22 --signal T2tt --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --beta noScaling --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p22_T2tt_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p22_T2tt_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p22_T2tt_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" --beta noScaling

python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"

# low S
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"

# mt2ll100
python systematicVariation_summed.py --plot_directory v0p19 --normalize --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100"
python systematicVariation_summed.py --plot_directory v0p19 --normalize --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"

# SR
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"

# SR mt2ll100
python systematicVariation_summed.py --plot_directory v0p19 --normalize --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"

