python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys None 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys jesTotalUp 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys jesTotalDown 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys PUVVUp 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys PUUp 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys unclustEnUp 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys unclustEnDown 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Down 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Up 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Down 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Up 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys DilepTriggerDown 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys DilepTriggerUp 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys LeptonSFDown 
python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys LeptonSFUp 
# python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys combine 

#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys None 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys jesTotalUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys jesTotalDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys PUVVUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys PUUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys unclustEnUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys unclustEnDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Down 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Up 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Down 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Up 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys DilepTriggerDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys DilepTriggerUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys LeptonSFDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys LeptonSFUp 
# python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1-onZ --reweightPU VUp --recoil VUp --selectSys combine 

#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys None 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUVVUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Down 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Up 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Down 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Up 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFUp 
## python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag1p-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys combine 
#
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys None 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUVVUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Down 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Up 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Down 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Up 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerUp 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFDown 
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFUp 
## python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys combine 
#
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys None
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUVVUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Down
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Up
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Down
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Up
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFUp
## python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet2p-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys combine
#
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys None
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUVVUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Down
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Up
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Down
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Up
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFUp
## python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys combine
#
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys None
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUVVUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Down
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Up
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Down
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Up
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFUp
## python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag0-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys combine
#
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys None
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUVVUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Down
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Up
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Down
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Up
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFUp
## python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig0To12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys combine
#
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys None
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys jesTotalDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUVVUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys PUUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys unclustEnDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Down
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_b_Up
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Down
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys BTag_SF_l_Up
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys DilepTriggerUp
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFDown
#python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys LeptonSFUp
## python systematicsPlots.py --era Run2018 --plot_directory v2 --selection lepSel-POGMetSig12-njet1-btag1-relIso0.12-looseLeptonVeto-mll20-dPhiJet0-dPhiJet1 --reweightPU VUp --recoil VUp --selectSys combine
#
