# DY CR
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
python systematicVariation_summed.py --plot_directory v0p19 --normalize --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"

# CR
python systematicVariation_summed.py --plot_directory v0p19 --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --beta noScaling --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" --beta noScaling

python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"

# low S
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ"
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --selection lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSigTo12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"

# mt2ll100
python systematicVariation_summed.py --plot_directory v0p19 --normalize --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-onZ-mt2ll100"
python systematicVariation_summed.py --plot_directory v0p19 --normalize --selection lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag0-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"

# SR
python systematicVariation_summed.py --plot_directory v0p19 --scaling mc --variation_scaling --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1"

# SR mt2ll100
python systematicVariation_summed.py --plot_directory v0p19 --normalize --signal T2tt --selection lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100 --directories "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2016/v0p19_T2tt_reweightPUCentral/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2017/v0p19_T2tt_reweightPUCentral/lepSel-badEEJetVeto-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100" "/afs/hephy.at/user/m/mdoppler/www/stopsDileptonLegacy/systematicPlots/Run2018/v0p19_T2tt_reweightPUVUp/lepSel-POGMetSig12-njet2p-btag1p-miniIso0.2-looseLeptonMiniIsoVeto-mll20-dPhiJet0-dPhiJet1-mt2ll100"

